[package]
name = "relly"
version = "0.1.0"
authors = ["doraneko94 <shuntaro94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.26"
serde = "1.0.129"
bincode = "1.3.3"
zerocopy = "0.5.0"
